services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secretpass
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
  backend:
      build: ./guess
      ports:
        - "5000:5000"
      environment:
        POSTGRES_DB: postgres
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: secretpass
        DATABASE_URL: postgres://postgres:secretpass@db:5432/postgres
      restart: always
      depends_on:
        - db
        
  frontend:
    build: ./
    ports:
      - "3000:80"
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    restart: always

volumes:
  db_data: